### ISSUE TITLE
Document the best way how to install the plugin

### ISSUE THREAD

**Issue by alexanderadam** [miZyind/mattermost-plugin-sentry#1]
What's the recommended way of installing the plugin with a Mattermost Docker installation?
Or do you maybe even have an example compose file or Ansible role that can be used?

**PS:** I guess it would also make sense to add it to [the Mattermost marketplace](https://mattermost.com/marketplace/sentry/), doesn't it? This way the [Python plugin](https://mattermost.com/marketplace/sentry/) wouldn't be all alone in the marketplace. 😉

**Comment by miZyind** [comment]
Thanks for your feedback!
This is just one of my experimental projects.
And I don't use Mattermost for a while.
I have no plan to continue maintenance and publishing to the marketplace.
